title:              개발블로그
email:              wwft09@naver.com
description:        정말로 개발자가 되고 싶어서 시작한
author:             Mina
baseurl:            ""
url:                "https://2min0r.github.io"

theme: jekyll-theme-clean-blog

# Social Profiles
twitter_username:
github_username:    2Min0r
facebook_username:  2min0r
instagram_username: 2.min0r

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site