title:              분홍발자국
email:              wwft09@naver.com
description:        폭신폭신 말랑말랑
author:             Mina
baseurl:            ""
url:                "https://2min0r.github.io"

theme: jekyll-theme-clean-blog

# Social Profiles
twitter_username:   SBootstrap
github_username:    2Min0r
facebook_username:  wwft09
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site